### PR TITLE
Hydraulic and SCADA/Wonderware plugins

### PR DESCRIPTION
**Pull request by ahuarte47**
This pull implements two plugins to respectively integrate Hydraulic and SCADA/Wonderware data models in the 52°North Sensor Observation Service (SOS).

image

These plugins add their entities as "virtual" SOS objects (Offerings, Procedures, FOIs, Observations and so on) using a mechanism of virtual injection of data in order to avoid to save them in the database managed by the 52°North SOS service.

The extensions catch the input WEB requests to create on-the-fly a set of available SOS objects to be inserted finally to the output WEB responses.

Each plugin provides a readme file and sample data to test.

This feature has been financed by GeoSmartCity Consortium (http://www.geosmartcity.eu) and Tracasa (http://www.tracasa.es/en)

### CODE REVIEW

**Comment by ahuarte47** [comment]
The pull provides two readme files to explain in more detail the extensions:

- [wonderware-modeling-sos-plugin - readme](https://github.com/ahuarte47/SOS/blob/27567039e74bce6e0903ade6f3c3e02e357b58ed/extensions/dynamic-modeling/wonderware-modeling-sos-plugin/README.md)
- [hydrology-modeling-sos-plugin - readme](https://github.com/ahuarte47/SOS/blob/14ed17115f8f4f1548b158d80b389909d505b312/extensions/dynamic-modeling/hydrology-modeling-sos-plugin/README.md)

**Comment by CarstenHollmann** [comment]
Hi Alvaro (@ahuarte47) ,

thanks for your contributions.

We had a look at your code and it looks like a nice feature to support the hydrology model (EPANET) and Wonderware.

However, we discoverd that you implemented a new data model to access the new datasource instead of using the 52N SOS DAO model and you use "virtual" objects which are injected on-the-fly to the requests and responses.

The issues we noticed are that you can not use the Hydraulic or Wonderware implementation as a dedicated datasource in the 52N SOS and the "virtual" injection may slow down the request/response processing.

Depending on the size of the "virtually" provided data, the virtual injection can slow down the request processing because for every request the content cache is extended. Especially the response of the GetCapabilities request becomes slower compared to an approach in which all required information is already contained in the cache. 

Because the 52N DAO model is not used, you can not install a 52N SOS with the Hydraulic or Wonderware model as a dedicated datasoure. But you always have to install a 52N SOS with the Hibernate DAO and a required database. Therefore, the access to the Hydraulic and Wonderware datasource should implement the 52N SOS DAO model.

Currently, the SOS architecture usually forsees only one DAO per SOS server: e.g. a Hibernate DAO, File based data storage DAO, etc. To ensure a good maintainability, the typical approach would be the implementation of an aggregation DAO which should support multiple sub DAOs, e.g Hibernate DAOs, Wonderware DAOs, etc. The aggregation DAO manages the merging of the information from the sub DAOs and forwards the requests to the sub DAO.

The benefits of this approach are that all information for the business logic and the Capabilities is already contained in the cache and you can use, for example, Wonderware as a single datasource in the 52N SOS. 

Therefore, we would not merge your pull request into the main development line of the 52N SOS and we recommend to discuss with us the requirements and how this can be integrated into the service. 
For now, we would suggest to put your extension into a dedicated branch. I could for this purpose create such a branch and subsequently you would send your pull request against this branch.

The new created branch, you would send your pull request against: [feature/dynamic_observable_objects](https://github.com/52North/SOS/tree/feature/dynamic_observable_objects)

Best,
Carsten

**Comment by ahuarte47** [comment]
Hi @CarstenHollmann, thanks for your review, I study your advices (about aggregation DAO achitecture) and I will try to apply them.

Thanks a lot!
Alvaro

**Comment by ahuarte47** [comment]
Hi @CarstenHollmann, I would like to explain the pull better. This pull contains some separated commits to be more didactic.

The two first commits are the only one who change the core of the service.

- [Operations using RequestOperatorContext](https://github.com/ahuarte47/SOS/commit/69767aab52bc1945768a810d334db1c28b607bd2):
Now, operations do not use the static reference of the ContentCache class, they use the new reference of the current request. IMHO this is a nice feature.

- [Allow override database ContentCache](https://github.com/ahuarte47/SOS/commit/df7566c604df7457bf0fbeea2953772439587e7a):
This commit only defines a new interface to change the content cache of the request. This change only runs when there are registered plugins implementing this interface, and they decide to do it. This new interface does not break the current API or current behavior.

Next commits are only used to implement the new plugins. The service has not dependencies with them.

- [API classes to inject dynamic observable objects](https://github.com/ahuarte47/SOS/commit/5bc081ae82787f3a85d21e7801737e0c72e0b748) and [Implements DynamicWritableCache methods](https://github.com/ahuarte47/SOS/commit/0ade5123a857409d83cb12403171c4d01a7a8cfa) define a new set of utility classes that the service does not manage. They are used by my new plugins.

>However, we discoverd that you implemented a new data model to access the new datasource instead of using the 52N SOS DAO model and you use "virtual" objects which are injected on-the-fly to the requests and responses.

>>As I said, this new data model does not affect the current core of the service. They are a set of utility classes shared by my new plugins. They could be used by other plugins to easily inject SOS objects, but they are optional, we can inject SOS objects to the ContentCache object as usual.

The other commits implement the hydrology model (EPANET) and Wonderware plugins.

About:

>Depending on the size of the "virtually" provided data, the virtual injection can slow down the request processing because for every request the content cache is extended. Especially the response of the GetCapabilities request becomes slower compared to an approach in which all required information is already contained in the cache.

>>You are right, the plugins clone the current cached ContentCache object for each request, but you can think the situation where the data of the EPANET or SCADA databases can not be managed in the available RAM. We have SCADA databases, or hydraulic networks, with millions of records. This trick to "on-the-fly" inject only the objects required by the request, avoids this issue.

>The benefits of this approach are that all information for the business logic and the Capabilities is already contained in the cache and you can use, for example, Wonderware as a single datasource in the 52N SOS.

>>My previous comment writes about this. The plugins read the filters (objectID, temporal and/or spatial filters) defined in the input requests and then use them to write the **only** required SOS objects that matches the filters. It is true that the GetCapabilities request could create a huge XML response, but there is a setting in the plugins to "hide" objects in this request type while the objects are available for the other request types.

I hope I have explain the reasons to implement the "on-the-fly" injection of data in this manner. I would love if you could look again this pull (especially the first two commits) to be integrated into main branch, of course, with any changes that you advice me.

Thanks in advance
Alvaro

**Pull request closed without merging**
