### PR TITLE
Settings JSON encoder: encode NULL if setting is null

### PR DESCRIPTION
**Pull request by shane-axiom**

### CODE REVIEW

**Comment by autermann** [comment]
Shane, could you explain your use case? Right now, I would propose to revert this commit.

If there is a `null`-`SettingDefinition`, that's a bug that should be handled in the SettingsManager. Handling this in the encoder is obfuscating the underlying problem and will make it hard to catch. 

Moreover, I don't think that the Javascript GUI builders can handle this...

**Comment by autermann** [comment]
That of course also applies to the `SettingValue`. `getValue()` may return `null`, but the wrapper never should be...

**Comment by shane-axiom** [comment]
I'm working on updating the IOOS SOS build to use the 4.2.0 release of the SOS and ran into a `NullPointerException` in `SettingDefinitionEncoder`'s `encodeValue` method (since apparently my settings database doesn't contain a certain key and needs to be updates. I added null handling to `encodeValue` and thought I should make the similar `encodeDefaultValue` null safe also.

The setting with the null value is `service.streaming.datasource`, which isn't in my default settings database and also doesn't seem to be in `misc/db/default_settings.sql`, which I use to initialize my settings database.

Admittedly this is a rare case that most people probably won't encounter, but I think it would still be a good idea to handle null setting values.  I'm just getting back into the SOS code after a long break now and I'm a little rusty. I'm fine with these null safe encoder changes being reverted, but where should the null setting checking happen? When the settings database is loaded?

**Comment by shane-axiom** [comment]
@autermann What if the [AbstractSettingsManager](https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/config/AbstractSettingsManager.java#L232) used a setting's default value (if available) when that setting wasn't found in the setting values instead of null (falling back to null if no default was available)?

https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/config/AbstractSettingsManager.java#L232

**Comment by shane-axiom** [comment]
@CarstenHollmann Also, I need a base "default" instance of the settings sqlite database to customize for IOOS builds. In the past I have [initialized a new database](https://github.com/ioos/i52n-sos/blob/master/misc/conf/build_conf_db.sh) with [misc/db/default_settings.sql](https://github.com/52North/SOS/blob/master/misc/db/default_settings.sql) and then applied IOOS customizations to that database. Should I instead start using [misc/conf/configuration.db](https://github.com/52North/SOS/blob/master/misc/conf/configuration.db) as my starting point? Or will [default_settings.sql](https://github.com/52North/SOS/blob/master/misc/db/default_settings.sql) be maintained in the future?

**Comment by shane-axiom** [comment]
Created an issue for default_settings.sql vs default_settings.db: https://github.com/52North/SOS/issues/224

Created a pull request to make AbstractSettingsManager use default setting values for missing settings: 
https://github.com/52North/SOS/pull/225

**Pull request merged**
