### PR TITLE
include Distribution/osgeolive

### PR DESCRIPTION
**Pull request by EHJ-52n**
I would like to integrate the `webapp-osgeo-live` in the main SOS repository. The adjustments are the following:

- additional setting for osgeo-live version (required for the assembled artefact)
- new submodule `webapp-osgeo-live`
- a pre-configurated set-up with
  - configuration.db
  - adjusted helgoland settings
  - adjusted jsClient settings
- json files with demo-data
- current state is merged with tag `v4.3.9`
- webapp name `52nSOS` and not `52n-sos-webapp`

## Optional Issues
- [ ] merge with latest development of this maintenance branch 
- [ ] move setttings and changed webapp name to own profile

What do you think?

### CODE REVIEW

**Comment by autermann** [comment]
Could you change back the license header? Because... I won't go through 2011 files :smile:

**Comment by autermann** [comment]
Would be fine for me, open a PR for that :wink:

**Comment by EHJ-52n** [comment]
@autermann 

Are you willing to merge now?

**Comment by EHJ-52n** [comment]
*ping*

**Comment by EHJ-52n** [comment]
@autermann @CarstenHollmann what is the state here?

**Comment by EHJ-52n** [comment]
...because to old and too many changes...

**Pull request closed without merging**
