### PR TITLE
RequestContext extended with accept-type and content-type

### PR DESCRIPTION
**Pull request by lestarcdog**
I extended the RequestContext class with two new fields.

I hope I did it right.

### CODE REVIEW

**Comment by nuest** [comment]
You have a different code layout, which creates changes where there weren't any (except new lines).

Did you install the 52N code formatter?

**Comment by lestarcdog** [comment]
Yes I use the codeformatter ["Java Conventions [52n]"](https://wiki.52north.org/pub/Documentation/WebHome/eclipse_code_formatter_52n_1.1.xml)

**Comment by CarstenHollmann** [comment]
The accepted content types for the responses should be defined in the 'Accept' header and not in the 'Accept-Encoding' header. See the [HTTPUtils.getAcceptHeader()](https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/util/http/HTTPUtils.java) which is used to get the 'Accept' header form the HTTP request.

It is also possible that several types are defined in the 'Accept' header. In that case the first type which is supported by the service will be used for the response.

**Comment by lestarcdog** [comment]
Okay this PR wasn't a success. Can I revoke it and and make a new one?

Btw, which code formatter should I use I have found only this one at this wiki site https://wiki.52north.org/bin/view/Documentation/WebHome

**Comment by lestarcdog** [comment]
Okay this PR wasn't a success. Can I revoke it and and make a new one?

Btw, which code formatter should I use I have found only this one at this wiki site https://wiki.52north.org/bin/view/Documentation/WebHome

**Comment by autermann** [comment]
You could also just add commits to this PR by pushing to the same branch. 

Regarding the formatter: I'm using Netbeans, so it's not available to me, just use 4 spaces indentation levels and put opening braces on the same line...

**Comment by nuest** [comment]
@autermann Can this be merged? Can you let @lestarcdog know what tests are required?

**Pull request merged**
