### PR TITLE
Convert line endings from CRLF to LF.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ This commit introduces no code change.
+ Please only commit files with *nix line endings to the repository.

### CODE REVIEW

**Comment by EHJ-52n** [comment]
Hi @johnjohndoe,
thank you for this contribution. Before we can accept your PR, we need a signed CLA from you.

Details about this procedure can be found on our homepage:

http://52north.org/about/licensing/cla-guidelines

Kind regards,
Eike

**Comment by johnjohndoe** [comment]
@CarstenHollmann Please feel free to convert the line endings on yourself and to close this pull request. No offence please but I consider signing the CLA as disproportional.

**Comment by CarstenHollmann** [comment]
Fixed in 6e9dbda

**Comment by johnjohndoe** [comment]
:+1:

**Comment by johnjohndoe** [comment]
Once again, the following files have been pushed with `CRLF` line endings to the repository:

* coding/sos-v20/pom.xml
* core/api/src/main/java/org/n52/sos/event/events/ResponseEvent.java
* extensions/do/core/pom.xml
* hibernate/common/pom.xml
* hibernate/dao/pom.xml
* hibernate/feature/pom.xml
* webapp/pom.xml

Please convert them to `LF` to avoid full file diffs.

**Comment by johnjohndoe** [comment]
Here is described [how the Git client can be configured to avoid formatting issues](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace) in the future.

**Pull request closed without merging**
